version: "3.0"

services:
  phpfpm:
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=lsQWeo2!pzx
      - MYSQL_DATABASE=stack
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:1.15.3-alpine
    depends_on:
      - phpfpm
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80